with-expecter: true
packages:
  gitlab.ozon.dev/yuweebix/homework-1/internal/cli:
    config:
      dir: ./mocks/cli
    interfaces:
      domain:
        config:
          outpkg: mocks
          filename: domain_mock.go
          mockname: MockDomain
      producer:
        config:
          outpkg: mocks
          filename: producer_mock.go
          mockname: MockProducer
