with-expecter: true
packages:
  gitlab.ozon.dev/yuweebix/homework-1/internal/api:
    config:
      dir: ./mocks/api
    interfaces:
      service:
        config:
          outpkg: mocks
          filename: service_mock.go
          mockname: MockService
  gitlab.ozon.dev/yuweebix/homework-1/internal/domain:
    config:
      dir: ./mocks/domain
    interfaces:
      storage:
        config:
          outpkg: mocks
          filename: storage_mock.go
          mockname: MockStorage
      cache:
        config:
          outpkg: mocks
          filename: cache_mock.go
          mockname: MockCache
