// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockProducer is an autogenerated mock type for the producer type
type MockProducer struct {
	mock.Mock
}

type MockProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProducer) EXPECT() *MockProducer_Expecter {
	return &MockProducer_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: message
func (_m *MockProducer) Send(message interface{}) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProducer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockProducer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - message interface{}
func (_e *MockProducer_Expecter) Send(message interface{}) *MockProducer_Send_Call {
	return &MockProducer_Send_Call{Call: _e.mock.On("Send", message)}
}

func (_c *MockProducer_Send_Call) Run(run func(message interface{})) *MockProducer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockProducer_Send_Call) Return(_a0 error) *MockProducer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProducer_Send_Call) RunAndReturn(run func(interface{}) error) *MockProducer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
